---
aws:
  access_key_id: access_key
  secret_access_key: secret_key
  bucket: chrondev
content_cdn: cdn.example.com
taxonomy:
  - name: News
    children:
      - name: University
        children:
          - name: Academics
          - name: Board of Trustees
  - name: Sports
  - name: Opinion
  - name: Recess
  - name: Towerview
